### ISSUE TITLE
Can't do anything with the plugin

### ISSUE THREAD

**Issue by hyochan** [NodeBB/nodebb-plugin-webhooks#11]
https://user-images.githubusercontent.com/27461460/190843001-e54f8b61-bbc8-48c6-94e1-42826f8656e1.mov

Hello. I've tried this plugin in nodebb and this doesn't seem to work.
I've posted recording on current status.

How do I set webhooks? I am using nodebb `v2.x`.

Thanks in advance

**Comment by barisusakli** [comment]
Plugin needed updating for nodebb 2.x, try with nodebb-plugin-webhooks@1.1.5

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-webhooks/commit/2e4dc5e0cd8bcd81d42bbce86ad88beca5480325

**Comment by hyochan** [comment]
Thanks so much for the prompt reply! It works 👍
